// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // WordPress project sidebar
  wordpressSidebar: [
    { type: 'doc', id: 'project-wordpress/intro', label: 'Introduction' },
    { type: 'doc', id: 'project-wordpress/architexture-diagram', label: 'Architecture Diagram' },
    { type: 'doc', id: 'project-wordpress/step-1-xampp', label: 'Step 1: Install XAMPP' },
    { type: 'doc', id: 'project-wordpress/step-2-wordpress', label: 'Step 2: Install WordPress' },
    { type: 'doc', id: 'project-wordpress/step-3-url-config', label: 'Step 3: URL Configuration' },
    { type: 'doc', id: 'project-wordpress/step-4-cloudflare-tunnel', label: 'Step 4: Cloudflare Tunnel' },
    { type: 'doc', id: 'project-wordpress/step-5-autorun-scripts', label: 'Step 5: Autorun Scripts' },
    { type: 'doc', id: 'project-wordpress/optional-fixes', label: 'Optional Fixes' },
    { type: 'doc', id: 'project-wordpress/checklist-and-tips', label: 'Checklist and Tips' },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
